name: Upload Release Asset

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install requirements
      run: |
        pip install --upgrade pip
        pip install -r Python/requirements/production.txt
        pip install -r requirements.txt

    - name: Test Python
      run: |
        cd Python
        python main.py --test

    - name: Build Python
      run: |
        cd Python
        python main.py

    - name: Build Courselet - Leitungsdimensionierung
      run: |
        pycourselet Leitungsdimensionierung

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
            Changes in this Release
            - First Change
            - Second Change
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "./Leitungsdimensionierung.courselet.zip"
        asset_name: "Leitungsdimensionierung.courselet.zip"
        asset_content_type: application/zip
